### ISSUE TITLE
ValueError: 549 is not in range

### ISSUE THREAD

**Issue by xiangxinyue** [CMUSTRUDEL/snorkel#9]
Traceback (most recent call last):
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 351, in get_loc
    return self._range.index(new_key)
ValueError: 549 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "training_functions.py", line 1325, in <module>
    if test_answers_final[0][i] == toxicity_v2_score[i]:
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 353, in get_loc
    raise KeyError(key) from err
KeyError: 549

**Comment by xiangxinyue** [comment]
543
Traceback (most recent call last):
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 351, in get_loc
    return self._range.index(new_key)
ValueError: 543 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "training_functions.py", line 1325, in <module>
    if test_answers_final[0][i] == toxicity_v2_score[i]:
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/home/xinyue/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 353, in get_loc
    raise KeyError(key) from err
KeyError: 543

**Comment by xiangxinyue** [comment]
fixed twice by changing the range but worry about potential changes of the dataset in the future
